apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g3j634o1o-nodejs
  janus-idp.io/tekton: g3j634o1o-nodejs
  backstage.io/kubernetes-id: g3j634o1o-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g3j634o1o-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
